USE nbarraza;

DROP TABLE IF EXISTS SSUCALENDAR;
CREATE TABLE SSUCALENDAR (CALENDAR_ID INTEGER NOT NULL, CALENDAR_TYPE VARCHAR(15) NOT NULL, CALENDAR_SUBTYPE VARCHAR(25) NOT NULL, DATE DATE NOT NULL, CALENDAR_DESCRIPTION LONG VARCHAR NOT NULL, PRIMARY KEY (CALENDAR_ID));

INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (1, 'academic', 'academicdate', '2016-11-15', 'Last day to petition to withdraw from a class with a 20 dollar administrative fee');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (2, 'academic', 'academicdate', '2016-11-15', 'Registration for Spring 2017 continues (by appointment only)');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (3, 'academic', 'academicdate', '2016-11-16', 'Registration for Spring 2017 continues (by appointment only)');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (4, 'academic', 'academicdate', '2016-11-17', 'Registration for Spring 2017 continues (by appointment only)');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (5, 'sport', 'volleyball', '2016-11-17', 'Women''s volleyball game at C C A A Championship Tournament in San Bernardino');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (6, 'academic', 'academicdate', '2016-11-18', 'Registration for Spring 2017 continues (by appointment only)');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (7, 'sport', 'soccer', '2016-11-18', 'Soccer game at N C A A Division 2 Championship Tournament (Day 1 of Third Round and Quarter final). For both Women and Men.');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (8, 'sport', 'volleyball', '2016-11-18', 'Women''s volleyball game at C C A A Championship Tournament, in San Bernardino');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (9, 'sport', 'basketball', '2016-11-18', 'Women''s basketball game against Dixie State, in Chico, at 5:30 P M');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (10, 'sport', 'basketball', '2016-11-18', 'Men''s basketball game against Saint Martin''s, at Sonoma State, at 7:30 P M');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (11, 'academic', 'academicdate', '2016-11-19', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (12, 'sport', 'soccer', '2016-11-19', 'Soccer game at N C A A Division 2 Championship Tournament (Day 2 of Third Round and Quarter final). For both Women and Men.');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (13, 'sport', 'volleyball', '2016-11-19', 'Women''s volleyball game at C C A A Championship Tournament, in San Bernardino');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (14, 'sport', 'crosscountry', '2016-11-19', 'Women''s cross country meet at N C A A Division 2 Championship, in Saint Leo, Florida');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (15, 'sport', 'basketball', '2016-11-19', 'Women''s basketball game against Western Oregon at 5:30 P M, at Chico ');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (16, 'sport', 'basketball', '2016-11-19', 'Men''s basketball tournament against San Bernardino and Saint Martins at 5:30 P M, at Sonoma State');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (17, 'sport', 'basketball', '2016-11-19', 'Men''s basketball game against Academy of Art at 7:30 P M, at Sonoma State');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (18, 'academic', 'academicdate', '2016-11-20', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (19, 'sport', 'soccer', '2016-11-20', 'Soccer game at N C A A Division 2 Championship Tournament (Day 3 of Third Round and Quarter final). For both Women and Men.');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (20, 'academic', 'academicdate', '2016-11-21', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (21, 'sport', 'soccer', '2016-11-21', 'Soccer game at N C A A Division 2 Championship Tournament (Day 4 of Third Round and Quarter final). For both Women and Men.');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (22, 'academic', 'academicdate', '2016-11-22', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (23, 'academic', 'academicdate', '2016-11-23', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (24, 'academic', 'holiday', '2016-11-23', 'First Day of Thanksgiving Break');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (25, 'academic', 'academicdate', '2016-11-24', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (26, 'academic', 'holiday', '2016-11-24', 'Second Day of Thanksgiving Break');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (27, 'academic', 'academicdate', '2016-11-25', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (28, 'academic', 'holiday', '2016-11-25', 'Last Day of Thanksgiving Break');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (29, 'sport', 'basketball', '2016-11-25', 'Men''s basketball game at Dixie State at 6:30 P M');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (30, 'academic', 'academicdate', '2016-11-26', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (31, 'sport', 'basketball', '2016-11-26', 'Men''s basketball game against Westminster College at 4 P M, at Dixie State');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (32, 'academic', 'academicdate', '2016-11-27', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (33, 'academic', 'academicdate', '2016-11-28', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (34, 'academic', 'academicdate', '2016-11-29', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (35, 'sport', 'basketball', '2016-11-29', 'Women''s basketball game at Menlo at 6 P M');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (36, 'academic', 'academicdate', '2016-11-30', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (37, 'academic', 'academicdate', '2016-12-01', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (38, 'academic', 'academicdate', '2016-12-01', 'The thesis deadline for December 2016 graduates');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (39, 'sport', 'soccer', '2016-12-01', 'NEED TO ADD');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (40, 'sport', 'basketball', '2016-12-01', 'Men''s basketball game at U C Santa Barbara at 7 P M');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (41, 'academic', 'academicdate', '2016-12-02', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (42, 'sport', 'soccer', '2016-12-02', 'NEED TO ADD');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (43, 'academic', 'academicdate', '2016-12-03', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (44, 'sport', 'soccer', '2016-12-03', 'NEED TO ADD');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (45, 'sport', 'basketball', '2016-12-03', 'Basketball game at Cal State L A. Women at 5:30 P M and Men at 7:30 P M');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (46, 'academic', 'academicdate', '2016-12-04', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (47, 'sport', 'soccer', '2016-12-04', 'NEED TO ADD');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (48, 'academic', 'academicdate', '2016-12-05', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (49, 'academic', 'academicdate', '2016-12-06', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (50, 'academic', 'academicdate', '2016-12-07', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (51, 'academic', 'academicdate', '2016-12-08', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (52, 'academic', 'academicdate', '2016-12-09', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (53, 'academic', 'academicdate', '2016-12-09', 'Last day for full term withdrawal with no refund');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (54, 'academic', 'academicdate', '2016-12-09', 'Last day of classes for the Fall 2016 semester');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (55, 'sport', 'basketball', '2016-12-09', 'Basketball game against San Francisco State at College of Marin. Women at 5:30 P M and Men at 7:30 P M');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (56, 'academic', 'academicdate', '2016-12-10', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (57, 'academic', 'academicdate', '2016-12-10', 'Withdrawals starting this date are considered Retroactive and need to follow the University''s withdrawal policy');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (58, 'sport', 'basketball', '2016-12-10', 'Basketball game against Cal State Monterey Bay at College of Marin. Women at 5:30 P M and Men at 7:30 P M');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (59, 'academic', 'academicdate', '2016-12-11', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (60, 'academic', 'academicdate', '2016-12-12', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (61, 'academic', 'academicdate', '2016-12-12', 'Finals');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (62, 'academic', 'academicdate', '2016-12-13', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (63, 'academic', 'academicdate', '2016-12-13', 'Finals');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (64, 'academic', 'academicdate', '2016-12-14', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (65, 'academic', 'academicdate', '2016-12-14', 'Finals');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (66, 'academic', 'academicdate', '2016-12-15', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (67, 'academic', 'academicdate', '2016-12-15', 'Finals');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (68, 'academic', 'academicdate', '2016-12-16', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (69, 'academic', 'academicdate', '2016-12-16', 'Finals');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (70, 'academic', 'academicdate', '2016-12-17', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (71, 'sport', 'basketball', '2016-12-17', 'Basketball game at Chico State. Women at 5:30 P M and Men at 7:30 P M');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (72, 'academic', 'academicdate', '2016-12-18', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (73, 'academic', 'academicdate', '2016-12-19', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (74, 'academic', 'academicdate', '2016-12-20', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (75, 'academic', 'academicdate', '2016-12-21', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (76, 'academic', 'academicdate', '2016-12-22', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (77, 'academic', 'academicdate', '2016-12-23', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (78, 'academic', 'academicdate', '2016-12-24', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (79, 'academic', 'academicdate', '2016-12-25', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (80, 'academic', 'academicdate', '2016-12-26', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (81, 'academic', 'academicdate', '2016-12-27', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (82, 'academic', 'academicdate', '2016-12-28', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (83, 'academic', 'academicdate', '2016-12-29', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (84, 'academic', 'academicdate', '2016-12-30', 'Registration for Spring 2017 continues');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (85, 'sport', 'basketball', '2016-12-30', 'Basketball game against Cal Poly Pomona at Santa Rosa Junior College. Women at 5:30 P M and Men at 7:30 P M');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (86, 'academic', 'academicdate', '2016-12-31', 'Registration for Spring 2017 ends');
INSERT INTO SSUCALENDAR (CALENDAR_ID, CALENDAR_TYPE, CALENDAR_SUBTYPE, DATE, CALENDAR_DESCRIPTION) 
	VALUES (87, 'sport', 'basketball', '2016-12-31', 'Basketball game against Cal State East Bay at Santa Rosa Junior College. Women at 5:30 P M and Men at 7:30 P M');

SELECT * FROM SSUCALENDAR ORDER BY CALENDAR_ID;

